#build the image and push to hub as rohanandlife/app2:v1before applying this manifest
apiVersion: v1
kind: Pod
metadata:
  name: app2
  labels:
    app: app2
spec:
  containers:
  - name: app2
    image: rohanraghu/app2:v1
    ports:
    - containerPort: 80
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
---
#service for app1
apiVersion: v1
kind: Service
metadata:
  name: service2
spec:
  selector:
    app: app2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: expense-ingress1
  annotations:
    #kubernetes.io/ingress.class: "alb"
    alb.ingress.kubernetes.io/scheme: internet-facing #internet-facing or internal
    alb.ingress.kubernetes.io/target-type: ip         #ip or instance; ip is default; meaning, the traffic will be routed to the ip of the target group
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:your-cert-arn
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/group.name: "expense-group" #same alb is used for every ingress with same group name
spec:
  ingressClassName: alb 
  rules:
  - host: app1.rohanandlife.site
    http:
      paths:
      - pathType: Prefix
        path: "/cart"
        backend:
          service:
            name: service2
            port:
              number: 80
